.TH IQRF-GATEWAY-WEBAPP-MANAGER 8 2023-01-23 "IQRF Gateway Webapp v2.5.0-rc3" "IQRF GW Manual"
.SH NAME
iqrf-gateway-webapp-manager \- manage IQRF Gateway Webapp from CLI
.SH DESCRIPTION
The
.B iqrf-gateway-webapp-manager
command manages IQRF Gateway Webapp from command line.
.SH SYNOPSIS
iqrf-gateway-webapp-manager [command] [options]
.SH COMMANDS
.nf
.TP
.BR list\fP
Lists all available commands
.TP
.BR api\-key:list\fP
Lists all existing API keys
.TP
.BR api\-key:add\fP " [\-d DESCRIPTION] [\-e EXPIRATION] [\-\-no\-formatting]"
Creates a new API key
.TP
.BR api\-key:delete\fP " [\-i ID]"
Removes an existing API key
.TP
.BR api\-key:edit\fP " [\-i ID] [\-d DESCRIPTION] [\-e EXPIRATION]"
Edits an existing API key
.TP
.BR database:create\fP
Creates database for webapp
.TP
.BR feature:list\fP
Lists all available features
.TP
.BR feature:enable\fP " [\<names\>...]"
Enables specified feature(s)
.TP
.BR feature:disable\fP " [\<names\>...]"
Disables specified features(s)
.TP
.BR mapping:list\fP
Lists all existing board mappings
.TP
.BR mapping:add\fP " [\-t TYPE] [\-N NAME] [\-I INTERFACE] [\-b BUS_PIN] [\-p PGM_PIN] [\-P POWER_PIN] [\-r BAUD_RATE]"
Adds a new board mapping
.TP
.BR mapping:edit\fP " [\-i ID] [\-t TYPE] [\-N NAME] [\-I INTERFACE] [\-b BUS_PIN] [\-p PGM_PIN] [\-P POWER_PIN] [\-r BAUD_RATE]"
Edits an existing board mapping
.TP
.BR mapping:remove\fP " [\-i ID]
Removes an existing board mapping
.TP
.BR migrations:migrate\fP
Executes database migration to the latest version
.TP
.BR nette:cache:purge\fP
Clears webapp cache
.TP
.BR user:list\fP
Lists all users
.TP
.BR user:add\fP " [\-u USERNAME] [\-p PASSWORD] [\-r ROLE] [\-l LANGUAGE]"
Adds a new user
.TP
.BR user:edit\fP " [\-u USERNAME] [\-r ROLE] [\-l LANGUAGE]"
Edits an existing user
.TP
.BR user:password\fP " [\-u USERNAME] [\-p PASSWORD]"
Changes a user's password
.TP
.BR user:remove\fP " [\-u USERNAME]"
Removes an existing user
.TP
.BR wireguard:list\fP
Lists all WireGuard VPN tunnels
.TP
.BR wireguard:activate\fP " \<name\>"
Activates specified WireGuard VPN tunnel
.TP
.BR wireguard:deactivate\fP " \<name\>"
Deactivates specified WireGuard VPN tunnel
.fi
.SH OPTIONS
.nf
.TP
.BR "General options"
.TQ
.BR \-h ", " \-\-help
Display this help message
.TP
.BR \-q ", " \-\-quiet
Do not output any message
.TP
.BR \-V ", " \-\-version
Display version of this application
.TP
.BR \-\-ansi
Force ANSI output
.TP
.BR \-\-no\-ansi
Disable ANSI output
.TP
.BR \-n ", " \-\-no\-interaction
Do not ask any interactive questions
.TP
.BR \-v|vv|vvv ", " \-\-verbose
Increase the verbosity of messages: -v for normal output, -vv for more verbose output, -vvv for debug output
.TP
.BR "API key commands:"
.TQ
.BR \-i ", " \-\-id " \fIID\fP"
API key ID
.TP
.BR \-d ", " \-\-description " \fIDESCRIPTION\fP"
API key description
.TP
.BR \-e ", " \-\-expiration " \fIEXPIRATION\fP"
API key expiration
.TP
.BR \-\-no\-formatting
Outputs API key without formatting
.TP
.BR "Mapping commands"
.TQ
.BR \-i ", " \-\-id " \fIID\fP"
Mapping ID
.TP
.BR \-t ", " \-\-type " \fITYPE\fP"
Mapping type
.TP
.BR \-N ", " \-\-name " \fINAME\fP"
Mapping name
.TP
.BR \-I ", " \-\-interface " \fIINTERFACE\fP"
Mapping device name
.TP
.BR \-b ", " \-\-bus-pin " \fIBUS_PIN\fP"
Mapping bus enable GPIO pin
.TP
.BR \-p ", " \-\-pgm-pin " \fIPGM_PIN\fP"
Mapping programming mode switch GPIO pin
.TP
.BR \-P ", " \-\-power-pin " \fIPOWER_PIN\fP"
Mapping power enable GPIO pin
.TP
.BR \-r ", " \-\-baud-rate " \fIBAUD_RATE\fP"
Mapping UART baud rate, optional argument unless the specified mapping type is "uart"
.TP
.BR "User commands:"
.TQ
.BR \-u ", " \-user ", " \-\-username " \fIUSERNAME\fP"
User's username
.TP
.BR \-p ", " \-pass ", " \-\-password " \fIPASSWORD\fP"
User's password
.TP
.BR \-r ", " \-role ", " \-\-role " \fIROLE\fP"
User's role
.TP
.BR \-l ", " \-lang ", " \-\-language " \fILANGUAGE\fP"
User's language
.fi
.SH LICENCE
This program is licensed under Apache License version 2.0.
.SH AUTHORS
.nf
Roman Ondráček <\fIroman.ondracek@iqrf.com\fP>
Karel Hanák <\fIkarel.hanak@microrisc.com\fP>
.SH COPYRIGHT
.nf
Copyright 2017\-2023 IQRF Tech s.r.o.
Copyright 2019\-2023 MICRORISC s.r.o.
.fi
