.TH IQRF-GATEWAY-WEBAPP-MANAGER 8 2020-10-25 "IQRF Gateway Webapp v2.1.0" "IQRF GW Manual"
.SH NAME
iqrf-gateway-webapp-manager \- manage IQRF Gateway Webapp from CLI
.SH DESCRIPTION
The
.B iqrf-gateway-webapp-manager
command manages IQRF Gateway Webapp from command line.
.SH SYNOPSIS
iqrf-gateway-webapp-manager [command] [options]
.SH COMMANDS
.nf
.TP
.BR iqrf-gateway-webapp-manager " \fIlist\fP"
Lists all available commands
.TP
.BR iqrf-gateway-webapp-manager " \fIuser:add\fP [\-u USERNAME] [\-p PASSWORD] [\-r ROLE] [\-l LANGUAGE]"
Adds a new user
.TP
.BR iqrf-gateway-webapp-manager " \fIuser:edit\fP [\-u USERNAME] [\-r ROLE] [\-l LANGUAGE]"
Edits an existing user
.TP
.BR iqrf-gateway-webapp-manager " \fIuser:list\fP"
Lists all users
.TP
.BR iqrf-gateway-webapp-manager " \fIuser:password\fP [\-u USERNAME] [\-p PASSWORD]"
Changes a user's password
.TP
.BR iqrf-gateway-webapp-manager " \fIuser:remove\fP [\-u USERNAME]"
Removes an existing user
.fi
.SH OPTIONS
.nf
.TP
.BR \-u ", " \-user ", " \-\-username " \fIUSERNAME\fP"
User's username
.TP
.BR \-p ", " \-pass ", " \-\-password " \fIPASSWORD\fP"
User's password
.TP
.BR \-r ", " \-role ", " \-\-role " \fIROLE\fP"
User's role
.TP
.BR \-l ", " \-lang ", " \-\-language " \fILANGUAGE\fP"
User's language
.fi
.SH LICENCE
This program is licensed under Apache License version 2.0.
.SH AUTHOR
Roman Ondráček <\fIroman.ondracek@iqrf.com\fP>
.SH COPYRIGHT
.nf
Copyright 2017 MICRORISC s.r.o.
Copyright 2017\-2019 IQRF Tech s.r.o.
.fi
