#!/bin/sh
# postrm script for iqrf-gateway-webapp

set -e

nginx_remove() {
	if [ -e /etc/nginx/sites-enabled/iqrf-daemon-webapp.localhost ] ; then
		rm /etc/nginx/sites-enabled/iqrf-daemon-webapp.localhost
	fi
	if [ -e /etc/nginx/sites-enabled/iqrf-gateway-webapp.localhost ] ; then
		rm /etc/nginx/sites-enabled/iqrf-gateway-webapp.localhost
	fi
	if [ -e /etc/nginx/sites-available/iqrf-daemon-webapp.localhost ] ; then
		rm /etc/nginx/sites-available/iqrf-daemon-webapp.localhost
	fi
	if [ -e /etc/nginx/sites-available/iqrf-gateway-webapp.localhost ] ; then
		rm /etc/nginx/sites-available/iqrf-gateway-webapp.localhost
	fi
	if deb-systemd-invoke is-enabled nginx.service ; then
    	deb-systemd-invoke reload nginx.service
    fi
}
sudoers_rule_remove() {
	if [ -e /etc/sudoers.d/iqrf-gateway-webapp ] ; then
		rm /etc/sudoers.d/iqrf-gateway-webapp
	fi
}

webapp_remove_config() {
	if [ -d /etc/iqrf-gateway-webapp/ ] ; then
		rm -rf /etc/iqrf-gateway-webapp/
	fi
}

webapp_remove_data() {
	if [ -d /usr/share/iqrf-gateway-webapp/ ] ; then
		rm -rf /usr/share/iqrf-gateway-webapp/
	fi
}

webapp_remove_manager() {
	if [ -e /usr/bin/iqrf-gateway-webapp-manager ] ; then
		rm /usr/bin/iqrf-gateway-webapp-manager
	fi
}

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
	nginx_remove
	webapp_remove_data
	webapp_remove_manager
	if [ "$1" = "purge" ]; then
		webapp_remove_config
	fi
	if [ -d /etc/sudoers.d/iqrf-gateway-webapp ] ; then
		rm -rf /etc/sudoers.d/iqrf-gateway-webapp
	fi
fi
