#!/bin/sh
# postrm script for iqrf-gateway-webapp

set -e

nginx_remove() {
	if [ -e /etc/nginx/sites-enabled/iqrf-gateway-webapp.localhost ] ; then
		rm /etc/nginx/sites-enabled/iqrf-gateway-webapp.localhost
	fi
	if [ -e /etc/nginx/sites-available/iqrf-gateway-webapp.localhost ] ; then
		rm /etc/nginx/sites-available/iqrf-gateway-webapp.localhost
	fi
	if deb-systemd-invoke is-enabled nginx.service ; then
		deb-systemd-invoke reload nginx.service
	fi
}

webapp_remove_cache() {
	if [ -d /var/cache/iqrf-gateway-webapp ] ; then
		rm -rf /var/cache/iqrf-gateway-webapp
	fi
}

webapp_remove_config() {
	if [ -d /etc/iqrf-gateway-webapp ] ; then
		rm -rf /etc/iqrf-gateway-webapp/
	fi
}

webapp_remove_data() {
	if [ -d /usr/share/iqrf-gateway-webapp ] ; then
		rm -rf /usr/share/iqrf-gateway-webapp/
	fi
}

webapp_remove_database() {
	if [ -d /var/lib/iqrf-gateway-webapp ] ; then
		rm -rf /var/lib/iqrf-gateway-webapp/
	fi
}

webapp_remove_logs() {
	if [ -d /var/log/iqrf-gateway-webapp/ ] ; then
		rm -rf /var/log/iqrf-gateway-webapp
	fi
}

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
	if [ -d /etc/nginx ] ; then
		nginx_remove
	fi
	webapp_remove_cache
	webapp_remove_data
	webapp_remove_logs
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper
			apache2_invoke dissite iqrf-gateway-webapp.conf || exit 1
		fi
	fi
fi

if [ "$1" = "purge" ]; then
	webapp_remove_config
	webapp_remove_database
fi
