#!/bin/sh
# preinst script for iqrf-gateway-webapp

set -e

if [ -e /etc/iqrf-gateway-webapp/sudoers ] ; then
	rm -rf /etc/iqrf-gateway-webapp/sudoers
fi

if [ ! -f /etc/sudoers.d/iqrf-gateway-webapp ] ; then
	rm -rf /etc/sudoers.d/iqrf-gateway-webapp
fi
