#!/bin/sh
# preinst script for iqrf-gateway-webapp

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in iqrf-gateway-webapp.conf  ; do
				apache2_invoke dissite $conf  || exit 1
			done
		fi
	fi
fi
