<h1>Console</h1>
<div class='tracy-inner'>
	<div class='tracy-inner-container'>
		<table class='tracy-sortable'>
			<tr>
				<th>Command</th>
				<th>Standard output</th>
				<th>Standard error output</th>
				<th>Exit code</th>
			</tr>
			<?php foreach ($this->stack->getCommands() as $command) : ?>
				<tr>
					<td>
						<pre><?= htmlspecialchars($command->getCommand(), ENT_QUOTES); ?></pre>
					</td>
					<td>
						<pre><?= htmlspecialchars($command->getStdout(), ENT_QUOTES); ?></pre>
					</td>
					<td>
						<pre><?= htmlspecialchars($command->getStderr(), ENT_QUOTES); ?></pre>
					</td>
					<td>
						<code><?= htmlspecialchars($command->getExitCode(), ENT_QUOTES); ?></code>
					</td>
				</tr>
			<?php endforeach; ?>
		</table>
	</div>
</div>
