/**
 * Copyright 2023-2025 MICRORISC s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { type AxiosResponse } from 'axios';

import {
	WireGuardIpStack,
	type WireGuardKeyPair,
	type WireGuardPeer,
	type WireGuardTunnelConfig,
	type WireGuardTunnelListEntry,
} from '../../types/Network';
import { BaseService } from '../BaseService';

/**
 * WireGuard service
 */
export class WireGuardService extends BaseService {

	/**
	 * Generates a new WireGuard key-pair
	 * @return {Promise<WireGuardKeyPair>} WireGuard key-pair
	 */
	public async generateKeyPair(): Promise<WireGuardKeyPair> {
		const response: AxiosResponse<WireGuardKeyPair> =
			await this.axiosInstance.post('/network/wireguard/keypair');
		return response.data;
	}

	/**
	 * Retrieves a list of existing WireGuard tunnels
	 * @return {Promise<WireGuardTunnelListEntry[]>} List of existing WireGuard tunnels
	 */
	public async listTunnels(): Promise<WireGuardTunnelListEntry[]> {
		const response: AxiosResponse<WireGuardTunnelListEntry[]> =
			await this.axiosInstance.get('/network/wireguard');
		return response.data;
	}

	/**
	 * Creates a new WireGuard tunnel
	 * @param {WireGuardTunnelConfig} config WireGuard tunnel configuration
	 * @return {WireGuardTunnelConfig} the uploaded tunnel config including tunnel ID generated by API
	 */
	public async createTunnel(config: WireGuardTunnelConfig): Promise<WireGuardTunnelConfig> {
		const response: AxiosResponse<WireGuardTunnelConfig> = await this.axiosInstance.post(
			'/network/wireguard',
			this.serializeTunnel(config),
		);
		return this.deserializeTunnel(response.data);
	}

	/**
	 * Updates an existing WireGuard tunnel
	 * @param {number} id WireGuard tunnel ID
	 * @param {WireGuardTunnelConfig} config WireGuard tunnel configuration
	 * @return {WireGuardTunnelConfig} the uploaded tunnel configuration
	 */
	public async updateTunnel(id: number, config: WireGuardTunnelConfig): Promise<WireGuardTunnelConfig> {
		const response: AxiosResponse<WireGuardTunnelConfig> = await this.axiosInstance.put(
			`/network/wireguard/${id.toString()}`,
			this.serializeTunnel(config),
		);
		return this.deserializeTunnel(response.data);
	}

	/**
	 * Deletes an existing WireGuard tunnel
	 * @param {number} id WireGuard tunnel ID
	 */
	public async deleteTunnel(id: number): Promise<void> {
		await this.axiosInstance.delete(`/network/wireguard/${id.toString()}`);
	}

	/**
	 * Retrieves an existing WireGuard tunnel configuration
	 * @param {number} id WireGuard tunnel ID
	 * @return {Promise<WireGuardTunnelConfig>} WireGuard tunnel configuration
	 */
	public async getTunnel(id: number): Promise<WireGuardTunnelConfig> {
		const response: AxiosResponse<WireGuardTunnelConfig> =
			await this.axiosInstance.get(`/network/wireguard/${id.toString()}`);
		return this.deserializeTunnel(response.data);
	}

	/**
	 * Activates an existing WireGuard tunnel
	 * @param {number} id WireGuard tunnel ID
	 */
	public async activateTunnel(id: number): Promise<void> {
		await this.axiosInstance.post(`/network/wireguard/${id.toString()}/activate`);
	}

	/**
	 * Deactivates an existing WireGuard tunnel
	 * @param {number} id WireGuard tunnel ID
	 */
	public async deactivateTunnel(id: number): Promise<void> {
		await this.axiosInstance.post(`/network/wireguard/${id.toString()}/deactivate`);
	}

	/**
	 * Enables an existing WireGuard tunnel
	 * @param {number} id WireGuard tunnel ID
	 */
	public async enableTunnel(id: number): Promise<void> {
		await this.axiosInstance.post(`/network/wireguard/${id.toString()}/enable`);
	}

	/**
	 * Disables an existing WireGuard tunnel
	 * @param {number} id WireGuard tunnel ID
	 */
	public async disableTunnel(id: number): Promise<void> {
		await this.axiosInstance.post(`/network/wireguard/${id.toString()}/disable`);
	}

	/**
	 * Creates new WireGuard peer
	 * @param {WireGuardPeer} peer configuration of the new peer
	 * @return {WireGuardPeer} created peer
	 */
	public async createPeer(peer: WireGuardPeer): Promise<WireGuardPeer> {
		const response: AxiosResponse<WireGuardPeer> = await this.axiosInstance.post(
			'/network/wireguard/peers',
			this.serializePeer(peer),
		);
		return this.deserializePeer(response.data);
	}

	/**
	 * Removes existing WireGuard peer
	 * @param {number} id ID of peer to remove
	 */
	public async removePeer(id: number): Promise<void> {
		await this.axiosInstance.delete(`/network/wireguard/peers/${id.toString()}`);
	}

	/**
	 * Update existing WireGuard peer
	 * @param {number} id ID of peer to update
	 * @param {WireGuardPeer} peer WireGuard peer configuration
	 * @return {WireGuardPeer} Updated WireGuard peer
	 */
	public async updatePeer(id: number, peer: WireGuardPeer): Promise<WireGuardPeer> {
		const response: AxiosResponse<WireGuardPeer> = await this.axiosInstance.put(
			`/network/wireguard/peers/${id.toString()}`,
			this.serializePeer(peer),
		);
		return this.deserializePeer(response.data);
	}

	/**
	 * Get WireGuard peer
	 * @param {number} id ID of peer to get
	 * @return {WireGuardPeer} Selected WireGuard peer
	 */
	public async getPeer(id: number): Promise<WireGuardPeer> {
		const response: AxiosResponse<WireGuardPeer> = await this.axiosInstance.get(`/network/wireguard/peers/${id.toString()}`);
		return this.deserializePeer(response.data);
	}

	/**
	 * Get WireGuard peers for given tunnel
	 * @param {number} tunnelId ID of tunnel to get peers for
	 * @return {WireGuardPeer[]} List of WireGuard peers configured for given interface
	 */
	public async getTunnelPeers(tunnelId: number): Promise<WireGuardPeer[]> {
		const response: AxiosResponse<WireGuardPeer[]> = await this.axiosInstance.get(`/network/wireguard/${tunnelId.toString()}/peers`);
		return response.data.map((peer) => this.deserializePeer(peer));
	}

	/**
	 * Gets list of all WireGuard peers
	 * @return {WireGuardPeer[]} List of all WireGuard peers
	 */
	public async getAllPeers(): Promise<WireGuardPeer[]> {
		const response: AxiosResponse<WireGuardPeer[]> = await this.axiosInstance.get('/network/wireguard/peers');
		return response.data.map((peer) => this.deserializePeer(peer));
	}

	/**
	 * Deserializes WireGuard tunnel configuration
	 * @param {WireGuardTunnelConfig} tunnel WireGuard tunnel configuration
	 * @return {WireGuardTunnelConfig} Deserialized WireGuard tunnel configuration
	 */
	private deserializeTunnel(tunnel: WireGuardTunnelConfig): WireGuardTunnelConfig {
		if (tunnel.ipv4 === undefined) {
			tunnel.stack = WireGuardIpStack.IPV6;
			// tunnel.ipv4 = { address: '', prefix: 24 };
		} else if (tunnel.ipv6 === undefined) {
			tunnel.stack = WireGuardIpStack.IPV4;
			// tunnel.ipv6 = { address: '', prefix: 64 };
		} else {
			tunnel.stack = WireGuardIpStack.DUAL;
		}
		return tunnel;
	}

	/**
	 * Serializes WireGuard tunnel configuration
	 * @param {WireGuardTunnelConfig} tunnel WireGuard tunnel configuration
	 * @return {WireGuardTunnelConfig} Serialized WireGuard tunnel configuration
	 */
	private serializeTunnel(tunnel: WireGuardTunnelConfig): WireGuardTunnelConfig {
		switch (tunnel.stack) {
			case WireGuardIpStack.IPV4:
				delete tunnel.ipv6;
				break;
			case WireGuardIpStack.IPV6:
				delete tunnel.ipv4;
				break;
		}
		delete tunnel.stack;
		delete tunnel.publicKey;
		return tunnel;
	}

	/**
	 * Deserializes WireGuard peer configuration
	 * @param {WireGuardPeer} peer WireGuard peer configuration
	 * @return {WireGuardPeer} Deserialized WireGuard peer configuration
	 */
	private deserializePeer(peer: WireGuardPeer): WireGuardPeer {
		return peer;
	}

	/**
	 * Serializes WireGuard peer configuration
	 * @param {WireGuardPeer} peer WireGuard peer configuration
	 * @return {WireGuardPeer} Serialized WireGuard peer configuration
	 */
	private serializePeer(peer: WireGuardPeer): WireGuardPeer {
		if (peer.psk === '' || peer.psk === undefined) {
			delete peer.psk;
		}
		return peer;
	}

}
